Repository cubixel/TutorPoint, pull requests merged in 2020-04, with the labels that each got.

#24 Iteration 3 Textchat
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  client/src/main/java/application/Launcher.java
  client/src/main/java/application/controller/MediaPlayerController.java
  client/src/main/java/application/controller/PresentationWindowController.java
  client/src/main/java/application/controller/TextWindowController.java
  client/src/main/java/application/controller/enums/TextRequestResult.java
  client/src/main/java/application/controller/services/MainConnection.java
  client/src/main/java/application/controller/services/TextService.java
  client/src/main/java/application/model/Message.java
  client/src/main/java/application/model/managers/MessageManager.java
  client/src/main/java/application/view/ViewFactory.java
  client/src/test/java/application/view/ViewFactoryTest.java
  server/src/main/java/services/enums/TextRequestResult.java
Labels: enhancement

#50 Iteration 4 Textchat
  client/src/main/java/application/controller/PresentationWindowController.java
  client/src/main/java/application/controller/TextChatWindowController.java
  client/src/main/java/application/controller/TextWindowController.java
  client/src/main/java/application/controller/enums/TextChatRequestResult.java
  client/src/main/java/application/controller/presentation/TimingManager.java
  client/src/main/java/application/controller/services/ListenerThread.java
  client/src/main/java/application/controller/services/TextChatRequestService.java
  client/src/main/java/application/controller/services/TextChatRequestSession.java
  client/src/main/java/application/controller/services/TextChatService.java
  client/src/main/java/application/controller/services/TextChatSession.java
  client/src/main/java/application/model/Message.java
  client/src/main/java/application/view/ViewFactory.java
  client/src/test/java/application/controller/presentation/TimingManagerTest.java
  server/src/main/java/TextChatHandler.java
  server/src/main/java/services/enums/TextRequestResult.java
Labels: bug

#51 Iteration 4 XML Presentation
  client/pom.xml
  client/src/main/java/application/controller/PresentationWindowController.java
  client/src/main/java/application/controller/presentation/ElementValidations.java
  client/src/main/java/application/controller/presentation/TimingManager.java
  client/src/main/java/application/controller/presentation/XmlHandler.java
  client/src/main/java/application/controller/services/ListenerThread.java
  client/src/main/resources/application/media/MyCoolPresentation.xml
  client/src/main/resources/application/media/downloads/MyCoolPresentation.xml
  client/src/main/resources/application/view/fxml/PresentationWindow.fxml
  pom.xml
  server/pom.xml
  server/src/main/java/ClientHandler.java
  server/src/main/java/PresentationHandler.java
  server/src/main/java/services/ClientNotifier.java
  server/src/main/java/sql/MySql.java
  server/src/main/resources/uploaded/presentations/placeholder.txt
  server/src/test/java/PresentationHandlerTest.java
Labels: enhancement

#49 Iteration 4 GUI
  client/src/main/java/application/controller/MainWindowController.java
  client/src/main/java/application/controller/RecentWindowController.java
  client/src/main/java/application/controller/StreamWindowController.java
  client/src/main/java/application/controller/services/LoginService.java
  client/src/main/java/application/controller/services/MainConnection.java
  client/src/main/java/application/controller/services/SubjectRequestService.java
  client/src/main/java/application/controller/services/TutorRequestService.java
  client/src/main/java/application/model/Subject.java
  client/src/main/java/application/model/managers/SubjectManager.java
  client/src/main/java/application/model/managers/TutorManager.java
  client/src/main/java/application/model/requests/SubjectRequest.java
  client/src/main/java/application/view/ViewInitialiser.java
  client/src/main/resources/application/view/fxml/MainWindow.fxml
  client/src/main/resources/application/view/fxml/StreamWindow.fxml
  client/src/main/resources/application/view/fxml/homeWindows/RecentWindow.fxml
  client/src/test/java/application/model/SubjectTest.java
  client/src/test/java/application/model/requests/SubjectRequestTest.java
  server/src/main/java/ClientHandler.java
  server/src/main/java/model/Subject.java
  server/src/main/java/model/requests/SubjectRequest.java
  server/src/main/java/services/ServerTools.java
  server/src/main/java/sql/MySql.java
  server/src/test/java/model/SubjectTest.java
  server/src/test/java/model/requests/SubjectRequestTest.java
  server/src/test/java/sql/MySqlQuickBuild.java
  server/src/test/java/sql/MySqlTest.java
Labels: enhancement

#52 Removed Testing Project
  pom.xml
  server/pom.xml
  testing/pom.xml
  testing/src/test/java/MainTopLevelTest
Labels: fix

#53 Add loggedInUsers
  README.md
  client/src/main/java/application/controller/MainWindowController.java
  client/src/main/java/application/view/ViewInitialiser.java
  server/src/main/java/ClientHandler.java
  server/src/main/java/DataServer.java
  server/src/main/java/MainServer.java
  server/src/main/java/PresentationHandler.java
  server/src/main/java/WhiteboardHandler.java
  server/src/test/java/ClientHandlerTest.java
  server/src/test/java/MainServerTest.java
Labels: enhancement

#54 Iteration 4 Whiteboard Fix
  client/src/main/java/application/Launcher.java
  client/src/main/java/application/controller/WhiteboardWindowController.java
  client/src/main/java/application/controller/services/ListenerThread.java
  client/src/main/java/application/controller/services/WhiteboardRequestService.java
  client/src/main/java/application/controller/services/WhiteboardRequestSession.java
  client/src/main/java/application/controller/services/WhiteboardService.java
  client/src/main/java/application/controller/services/WhiteboardSession.java
  client/src/main/java/application/model/Whiteboard.java
  client/src/main/java/application/model/requests/WhiteboardRequest.java
  client/src/main/java/application/view/ViewFactory.java
  client/src/test/java/application/controller/GuiTests.java
  server/src/main/java/ClientHandler.java
  server/src/main/java/WhiteboardHandler.java
  server/src/main/java/model/requests/WhiteboardRequest.java
  server/src/main/java/services/ClientNotifier.java
Labels: fix
