Repository cubixel/TutorPoint, pull requests merged in 2020-03, with the labels that each got.

#3 Iteration 1 Whiteboard
  .gitignore
  README.md
  client/src/main/java/application/Launcher.java
  client/src/main/java/application/controller/WhiteboardWindowController.java
  client/src/main/resources/application/media/icons/pencil_icon.png
  client/src/main/resources/application/media/icons/shape_icon.png
  client/src/main/resources/application/media/icons/text_icon.png
  client/src/main/resources/application/view/fxml/WhiteboardWindow.fxml
  client/src/test/java/application/controller/GuiTests.java
  client/src/test/java/application/controller/WhiteboardWindowControllerTest.java
Labels: enhancement

#5 Iteration 1 XML
  .gitignore
  checkstyleGoogle.xml
  client/src/main/java/application/Launcher.java
  client/src/main/java/application/controller/BaseController.java
  client/src/main/java/application/controller/LoginWindowController.java
  client/src/main/java/application/controller/MainWindowController.java
  client/src/main/java/application/controller/MediaPlayerController.java
  client/src/main/java/application/controller/OptionsWindowController.java
  client/src/main/java/application/controller/PresentationWindowController.java
  client/src/main/java/application/controller/RegisterWindowController.java
  client/src/main/java/application/controller/WebcamWindowController.java
  client/src/main/java/application/controller/WhiteboardWindowController.java
  client/src/main/java/application/controller/presentation/ElementValidations.java
  client/src/main/java/application/controller/presentation/ImageHandler.java
  client/src/main/java/application/controller/presentation/PresentationObject.java
  client/src/main/java/application/controller/presentation/PresentationSlide.java
  client/src/main/java/application/controller/services/Heartbeat.java
  client/src/main/java/application/controller/services/ImageHandler.java
  client/src/main/java/application/controller/services/LoginService.java
  client/src/main/java/application/controller/services/MainConnection.java
  client/src/main/java/application/controller/services/RegisterService.java
  client/src/main/java/application/controller/services/Security.java
  client/src/main/java/application/controller/services/XmlHandler.java
  client/src/main/java/application/model/account/Account.java
  client/src/main/java/application/view/ViewFactory.java
  client/src/main/java/application/view/ViewInitialiser.java
  client/src/main/java/module-info.java
  client/src/main/resources/application/media/TestXML.xml
  client/src/main/resources/application/media/TestXMLBadDuration.xml
  client/src/main/resources/application/media/TestXMLBadID.xml
  client/src/main/resources/application/media/TestXMLInvalidText.xml
  client/src/main/resources/application/media/TestXMLNoAttributes.xml
  client/src/main/resources/application/media/TestXMLNoDuration.xml
  client/src/main/resources/application/media/TestXMLNoID.xml
  client/src/main/resources/application/media/TestXMLValidText.xml
  client/src/test/java/application/controller/GuiTests.java
  client/src/test/java/application/controller/LoginWindowControllerTest.java
  client/src/test/java/application/controller/RegisterWindowControllerTest.java
  client/src/test/java/application/controller/presentation/ImageHandlerTest.java
  client/src/test/java/application/controller/presentation/PresentationObjectTest.java
  client/src/test/java/application/controller/presentation/PresentationSlideTest.java
  client/src/test/java/application/controller/services/ImageHandlerTest.java
  client/src/test/java/application/controller/services/MainConnectionTest.java
  client/src/test/java/application/controller/services/SecurityTest.java
  client/src/test/java/application/controller/services/XmlHandlerTest.java
  client/src/test/java/application/model/account/AccountTest.java
  client/src/test/java/application/view/ViewFactoryTest.java
  client/src/test/java/application/view/ViewInitialiserTest.java
  server/src/main/java/ClientHandler.java
  server/src/main/java/MainServer.java
  server/src/main/java/sql/MySQL.java
  server/src/main/java/sql/MySql.java
  server/src/main/java/user/User.java
  server/src/test/java/ClientHandlerTest.java
  server/src/test/java/sql/MySQLTest.java
  server/src/test/java/sql/MySqlTest.java
  testing/src/test/java/MainTopLevelTest.java
Labels: enhancement

#7 Merge Testing back to Development
  .vscode/settings.json
  README.md
  client/src/main/java/application/controller/LoginWindowController.java
  client/src/main/java/application/controller/services/MainConnection.java
  client/src/main/resources/application/model/PlaceHolder.txt
  client/src/main/resources/application/model/userLoggedIn.txt
  client/src/test/java/application/controller/LoginWindowControllerTest.java
  client/src/test/java/application/controller/services/HeartbeatTest.java
Labels: enhancement

#11 Revert README
  README.md
Labels: fix

#16 Iteration 2 GUI
  .idea/sqldialects.xml
  client/src/main/java/application/Launcher.java
  client/src/main/java/application/controller/BaseController.java
  client/src/main/java/application/controller/LoginWindowController.java
  client/src/main/java/application/controller/MainWindowController.java
  client/src/main/java/application/controller/MediaPlayerController.java
  client/src/main/java/application/controller/RegisterWindowController.java
  client/src/main/java/application/controller/StreamWindowController.java
  client/src/main/java/application/controller/services/MainConnection.java
  client/src/main/java/application/controller/services/SubjectRenderer.java
  client/src/main/java/application/controller/services/SubjectRequestService.java
  client/src/main/java/application/view/ViewFactory.java
  client/src/main/java/application/view/ViewInitialiser.java
  client/src/main/resources/application/view/css/defaultTheme.css
  client/src/main/resources/application/view/fxml/MainWindow.fxml
  client/src/main/resources/application/view/fxml/OptionsWindow.fxml
  client/src/main/resources/application/view/fxml/StreamWindow.fxml
  client/src/main/resources/application/view/fxml/WhiteboardWindow.fxml
  client/src/main/resources/logback.xml
  client/src/test/java/application/controller/GuiTests.java
  client/src/test/java/application/controller/LoginWindowControllerTest.java
  client/src/test/java/application/controller/RegisterWindowControllerTest.java
  client/src/test/java/application/controller/StreamWindowControllerTest.java
  client/src/test/java/application/controller/services/LoginServiceTest.java
  client/src/test/java/application/controller/services/MainConnectionTest.java
  client/src/test/java/application/controller/services/SubjectRendererTest.java
  client/src/test/java/application/controller/services/SubjectRequestServiceTest.java
  client/src/test/java/application/view/ViewFactoryTest.java
  client/src/test/java/application/view/ViewInitialiserTest.java
  server/src/main/java/ClientHandler.java
  server/src/main/java/model/managers/SubjectManager.java
  server/src/main/java/services/ServerTools.java
  server/src/test/java/ClientHandlerTest.java
Labels: enhancement, fix

#17 Iteration 2 Whiteboard
  .gitignore
  .idea/misc.xml
  client/src/main/java/application/controller/WhiteboardWindowController.java
  client/src/main/java/application/controller/enums/WhiteboardRenderResult.java
  client/src/main/java/application/controller/services/WhiteboardService.java
  client/src/main/java/application/controller/services/WhiteboardSession.java
  client/src/main/java/application/model/Whiteboard.java
  client/src/main/java/application/view/ViewFactory.java
  client/src/main/resources/application/media/icons/rubber_icon.png
  client/src/main/resources/application/view/fxml/WhiteboardWindow.fxml
  client/src/test/java/application/controller/GuiTests.java
  client/src/test/java/application/controller/WhiteboardWindowControllerTest.java
  client/src/test/java/application/controller/services/WhiteboardServiceTest.java
  server/pom.xml
  server/src/main/java/ClientHandler.java
  server/src/main/java/WhiteboardHandler.java
Labels: enhancement

#18 Xml branch
  client/src/main/java/application/controller/presentation/ElementValidations.java
  client/src/main/java/application/controller/presentation/PresentationSlide.java
  client/src/main/resources/application/media/XML/TestXMLInvalidAudio.xml
  client/src/main/resources/application/media/XML/TestXMLInvalidLine.xml
  client/src/main/resources/application/media/XML/TestXMLInvalidShading.xml
  client/src/main/resources/application/media/XML/TestXMLInvalidShape.xml
  client/src/main/resources/application/media/XML/TestXMLInvalidText.xml
  client/src/main/resources/application/media/XML/TestXMLValidAudio.xml
  client/src/main/resources/application/media/XML/TestXMLValidLine.xml
  client/src/main/resources/application/media/XML/TestXMLValidShading.xml
  client/src/main/resources/application/media/XML/TestXMLValidShape.xml
  client/src/test/java/application/controller/presentation/PresentationSlideTest.java
Labels: enhancement

#19 Video tp007 tp017
  .idea/.gitignore
  .idea/Software-Engineering-Project.iml
  .idea/dictionaries/there.xml
  .idea/encodings.xml
  .idea/modules.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  client/src/main/java/application/controller/services/VideoHandler.java
  client/src/main/java/application/controller/services/VideoReqResult.java
Labels: enhancement
